#!/bin/sh
THISFILE="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
THISDIR=$(dirname $THISFILE)
LOGDIR=/var/log/dsniff/
mkdir /var/log/dsniff/ > /dev/null 2>&1
ln -s $THISDIR/dsniff-daemon.sh /usr/sbin/dsniff-daemon
ln -s $THISDIR/dsniff-daemon.init /etc/init.d/dsniff-daemon
ln -s $THISDIR/dsniff-daemon.conf /etc/dsniff-daemon.conf
